### ISSUE TITLE
Add term labels in first columns 

### ISSUE THREAD

**Issue by agbeltran** [FAIRsharing/JSONschema-compare-and-view#6]
The label should be a link (as per #4) and we need to get the term labels using the OLS API. 

We can deal with schema.org annotations separately, as schema.org is not in OLS.

**Comment by agbeltran** [comment]
https://www.ebi.ac.uk/ols/docs/api

**Comment by agbeltran** [comment]
Relying on https://github.com/FAIRsharing/jsonldschema/issues/84, we will now have this info in the input files

**Comment by terazus** [comment]
Closing, this is a duplicated of #2
